sudo: false
language: cpp

env:
  global:
    - SDK_BUILD=258
    - secure: "K8VKIZ5cA/R7pJ30MMQwyiFUPrXPC0fQeb7SYZ55/8aVVcF2EO23GxlGiTBO7ve9u9KrWnyvBcJpUeqMs6YI1T0QXX73hfJN84DJZ9EImua+WhbhFUUj/MhVysFmiXdtmdhoyF4cTEg7aKnRSoqz/KreKslSpe/N2Opx/86CVVJMk5OL0RgjnfgWiaDNaW3HsXCOjZM9oFmF/ZYEu10r9ZtMu4BcePijTP1RUvvefZeLMT7smvpZhVpKc7/fMbWRm1iggfB1WTQNIUvDWIYPfTTubOOg5m+Zu8sSFhrDNJDZ0if+bZGEC7Xv2bZNIDb8O+NA5Dh2rCFbDJx8NwbLJHbNXrJVQQ0bYddqB8kJy2hsVJdOV7nT5OrWMdcIGH2wmCf6P5gXRzC6GZ+qPZwZZ2CvcQXSQdjd4US8J/jRyQxTJZj1acyxFZBJnwen0ruo/ajDEJMbkzG/Ysxa3p6xfB27mbYjGSRA3bnP7HYXC6ULXDF+MnEpD9LjBG94ruWrS6g+2h49aZYEUxxQ8OIvC6vmcSu5SKEsVcMC0dtv7OaL2Kzi639ls79KzR0f3TOIuoWKatzkA7h8/yAtzDq8VBZSEc2PAlsLQ4C7R0c313JiuCaXxQ1jikwJfNA3rrxkzSmBDVdI/7Uhce5R7Yw+LTi8oPhewF/iET7pT7pqavw=" 
    
matrix:
    include:
        - os: linux
          env: SDK_VERSION=1.5.0
        - os: linux
          env: SDK_VERSION=2.0.0
          
git:
  submodules: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:     
      - bsdtar
  coverity_scan:
    project:
      name: $TRAVIS_REPO_SLUG
      version: $TRAVIS_COMMIT
    build_command: make -C $SMING_HOME
    branch_pattern: coverity_scan
    notification_email: slav@attachix.com

install:
  - if [ "$SDK_VERSION" != "2.0.0" ] && [ "$TRAVIS_OS_NAME" == "osx" ]; then export SDK_FILE_NAME="esp-alt-sdk-v${SDK_VERSION}.${SDK_BUILD}-macos-x86_64.zip"; fi
  - if [ "$SDK_VERSION" != "2.0.0" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export SDK_FILE_NAME="esp-alt-sdk-v${SDK_VERSION}.${SDK_BUILD}-linux-x86_64.tar.gz"; fi
  - mkdir -p $TRAVIS_BUILD_DIR/opt/esp-alt-sdk
  - if [ "$SDK_VERSION" != "2.0.0" ]; then wget https://bintray.com/artifact/download/kireevco/generic/${SDK_FILE_NAME}; fi
  - if [ "$SDK_VERSION" != "2.0.0" ]; then bsdtar -xf ${SDK_FILE_NAME} -C $TRAVIS_BUILD_DIR/opt/esp-alt-sdk; fi
  - if [ "$SDK_VERSION" == "2.0.0" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://github.com/nodemcu/nodemcu-firmware/raw/master/tools/esp-open-sdk.tar.xz; tar -Jxvf esp-open-sdk.tar.xz; ln -s `pwd`/esp-open-sdk/xtensa-lx106-elf $TRAVIS_BUILD_DIR/opt/esp-alt-sdk/. ; fi
  - if [ "$SDK_VERSION" == "2.0.0" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then wget http://bbs.espressif.com/download/file.php?id=1690 -O sdk.zip; unzip sdk.zip; ln -s `pwd`/ESP8266_NONOS_SDK/ $TRAVIS_BUILD_DIR/opt/esp-alt-sdk/sdk; fi
  - export CHANGED_FILES=`git diff --diff-filter=AMD HEAD HEAD^ --name-only`
  - export CHANGED_PROJECTS=`for i in $CHANGED_FILES; do echo "$i" |  grep '^samples/' | cut -d'/' -f2; done | uniq`
  - export SMING_HOME=$TRAVIS_BUILD_DIR/Sming
  - export ESP_HOME=$TRAVIS_BUILD_DIR/opt/esp-alt-sdk  
  - export PATH=$PATH:$ESP_HOME/xtensa-lx106-elf/bin:$ESP_HOME/utils/:$SMING_HOME/../.travis/tools
script:
  - if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then
      echo "Skipping build/test on 'coverity_scan' branch.";
      exit 0;
    fi
  - cd $SMING_HOME
  - make test 
  - cd $SMING_HOME/../
  - export SMING_HAS_CHANGED=`for i in $CHANGED_FILES; do  if [[ $i == Sming/* ]]; then echo 1; break; fi; done`
  - if [ ! -z "$SMING_HAS_CHANGED" ]; then CHANGED_PROJECTS=`cd $SMING_HOME/../samples; ls -d *`; fi
  - for i in $CHANGED_PROJECTS; do echo "Compiling $i"; make -C "samples/$i"; if [ $? -ne 0 ]; then exit 1; fi; done
  - cd $SMING_HOME
  - make clean samples-clean
  - make ENABLE_GDB=1
  - make Basic_Debug
  - make clean samples-clean
  - make ENABLE_CUSTOM_HEAP=1
  - make Basic_Blink ENABLE_CUSTOM_HEAP=1
  - make clean samples-clean
  - make ENABLE_CUSTOM_LWIP=1; make samples ENABLE_CUSTOM_LWIP=1
